### ISSUE TITLE
springboot-kafka-storm的pom文件有误，idea无法正确加载配置文件

### ISSUE THREAD

**Issue by xuergou123** [xuwujing/springBoot-study#25]
正确如下
![image](https://user-images.githubusercontent.com/38751642/102586747-a7481500-4145-11eb-856c-ce26ca075a4d.png)

**Comment by xuergou123** [comment]
<resources>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>*.properties</include>
					<include>*.xml</include>
					<include>*.tld</include>
					<include>**/*.*</include>
				</includes>
				<filtering>false</filtering>
			</resource>
		</resources>

**Comment by xuwujing** [comment]
感谢提醒
