### ISSUE TITLE
请问这个问题怎么处理？ Error: Could not find or load main class com.pancm.Application

### ISSUE THREAD

**Issue by winer632** [xuwujing/springBoot-study#5]
[root@centos_0 ~]# storm jar ./springboot-kafka-storm-0.0.1-SNAPSHOT.jar com.pancm.Application myStorm
Running: /usr/java/jdk1.8.0_172-amd64/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/opt/storm -Dstorm.log.dir=/opt/storm/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /opt/storm/*:/opt/storm/lib/*:/opt/storm/extlib/*:./springboot-kafka-storm-0.0.1-SNAPSHOT.jar:/opt/storm/conf:/opt/storm/bin -Dstorm.jar=./springboot-kafka-storm-0.0.1-SNAPSHOT.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} com.pancm.Application myStorm
Error: Could not find or load main class com.pancm.Application
[root@centos_0 ~]# 
[root@centos_0 ~]# ll
total 512628
-rw-------. 1 root root      2757 May 10 02:41 anaconda-ks.cfg
-rw-r--r--. 1 root root 169713198 May 13 02:44 apache-storm-1.2.1.tar.gz
-rw-r--r--. 1 root root 175274374 May 13 01:38 jdk-8u172-linux-x64.rpm
-rw-r--r--. 1 root root  56969154 May 13 19:18 kafka_2.11-1.1.0.tgz
-rw-r--r--. 1 root root   1910835 May 13 02:52 libsodium-1.0.16.tar.gz
-rw-r--r--. 1 root root      6140 Nov 11  2015 mysql-community-release-el7-5.noarch.rpm
-rw-------. 1 root root      1062 May 14 22:52 nohup.out
-rwxrwxrwx. 1 root root  83037465 May 15 00:42 springboot-kafka-storm-0.0.1-SNAPSHOT.jar
-rw-r--r--. 1 root root        63 May 13 21:52 temp.txt
-rw-r--r--. 1 root root   1326780 May 13 02:56 zeromq-4.2.3.tar.gz
-rw-r--r--. 1 root root  36667596 May 13 02:06 zookeeper-3.4.12.tar.gz
[root@centos_0 ~]#

**Comment by xuwujing** [comment]
是storm方式在linux环境启动吗？
你是怎么打包的呢？看下打包之后jar程序结构是怎么样的。

**Comment by wurangbo** [comment]
我者也有同样的问题，是在linux下启动的，本地模式没有问题
