### ISSUE TITLE
请教下springboot-kafka-storm提交集群后无法访问自己编写的spout、bolt类的问题

### ISSUE THREAD

**Issue by lc418401552** [xuwujing/springBoot-study#6]
楼主你好！ 首先非常感谢你提供的思路以及demo。
我在本地测试可行，但是在提交集群后出现找不到自己编写的spout、bolt类，请问你有遇到过这种情况吗？
![image](https://user-images.githubusercontent.com/22512453/43063850-c14ff3ac-8e8f-11e8-845d-ccfb51a5b8bb.png)
我通过spring-boot-maven-plugin打包，打包后目录是这样：
![image](https://user-images.githubusercontent.com/22512453/43063916-fda08466-8e8f-11e8-8a6d-c7684d620712.png)

**Comment by xuwujing** [comment]
很抱歉，我没有遇到过这种问题。

**Comment by l06066hb** [comment]
遇到同样的问题 请问解决了么@lc418401552

**Comment by xuwujing** [comment]
@l06066hb 请看第一个issue，问题已经解决了！

**Comment by l06066hb** [comment]
额  是通过第一个issue的方式提交到集群的 不过通过springboot方式打的包结构里有boot-inf  work的日志中始终找不到spout和bolt  有过类似的经历么  我换成maven-shade-plugin打成普通包还是有问题

**Comment by xuwujing** [comment]
@l06066hb 你的spout和bolt是用new方式的，还是通过注解方式的？这个问题在第一个提issue的网友中，好像没有遇到，他那边是这样改之后就可以运行， 我这边没有storm环境，因此暂时无法进行解决，只能给你提一些思路了。

**Comment by l06066hb** [comment]
spout和bolt里的bean是手动获取的 不过现在和楼主报的错一样 直接就找不到类...

**Comment by xuwujing** [comment]
刚刚翻了下笔记，发现了解决办法。如果spout和bolt在使用spring ioc注入的时候无法拿到bean，此时可以动态的获取bean，并且将得到的对象改成公共静态即可。

**Comment by l06066hb** [comment]
情况有些不太一样  现在bean是动态获取的 不过目前还没到找不到业务bean   找不到是spout和bolt

**Comment by xuwujing** [comment]
@lc418401552 这种情况还真的没遇到过。你问下Tomorrow网友，也就是最上面提出的那个issue的网友，或许他可以给出解决办法。

**Comment by l06066hb** [comment]
好的  非常感谢

**Comment by stonezpl** [comment]
> 好的 非常感谢

想问下您，这个找不到类的问题你后来找到原因了吗
