### ISSUE TITLE
想问下 spring boot+jsp 中静态资源 例如 img css js 该怎么放

### ISSUE THREAD

**Issue by kyytyp** [xuwujing/springBoot-study#9]
现在我的jsp是可以访问 但是其他静态文件无法访问到
jsp是放到webapp的web-inf下面的

**Comment by xuwujing** [comment]
应该是可以访问的，你看下代码的路径和请求的路径是否正确。
我这边是在webapp目录下新建一个static文件夹，和web-inf同级，然后在这个文件夹下新建css、img、js等文件夹，希望能够对你有所帮助。

**Comment by kyytyp** [comment]
> 应该是可以访问的，你看下代码的路径和请求的路径是否正确。
> 我这边是在web应用程序目录下新建一个静态的文件夹，和WEB-INF同级，然后在这个文件夹下新建CSS，IMG ，JS等文件夹，希望能够对你有所帮助。

谢谢你的回复 现在可以访问了  我一直想着jsp要跟的img等放到同一目录下 这个思路有点问题 
再次表示感谢
